create sequence t_artists_SEQ start with 1 increment by 50;
create sequence t_customers_SEQ start with 1 increment by 50;
create sequence t_items_SEQ start with 1 increment by 50;
create sequence t_publishers_SEQ start with 1 increment by 50;
create sequence t_tracks_SEQ start with 1 increment by 50;
create table t_artists (created_date timestamp(6) with time zone not null, id bigint not null, name varchar(100) not null, bio varchar(3000), primary key (id));
create table t_books (nb_of_pages integer, publication_date date, id bigint not null, publisher_id bigint, isbn varchar(15), language varchar(20) check (language in ('ENGLISH','FRANCH','VIETNAMESE')), primary key (id));
create table t_cds (id bigint not null, genre varchar(100), music_company varchar(255), primary key (id));
create table t_customers (created_date timestamp(6) with time zone, id bigint not null, name varchar(50) not null, email varchar(100) not null unique, primary key (id));
create table t_items (price numeric(38,2) not null, artist_id bigint, created_date timestamp(6) with time zone not null, id bigint not null, title varchar(1000) not null, description varchar(3000), primary key (id));
create table t_publishers (created_date timestamp(6) with time zone not null, id bigint not null, name varchar(50) not null, primary key (id));
create table t_tracks (duration numeric(21,0) not null, cd_id bigint, created_date timestamp(6) with time zone, id bigint not null, title varchar(255) not null, primary key (id));
alter table if exists t_books add constraint FK6o38njp1r3q0byrrq7b6eqwd4 foreign key (publisher_id) references t_publishers;
alter table if exists t_books add constraint FKqhbwk9qekl2a77l2b624snm14 foreign key (id) references t_items;
alter table if exists t_cds add constraint FKq973yu2pg6p22v1k1t1yehtxb foreign key (id) references t_items;
alter table if exists t_items add constraint FK82l9m36t1j2xpsba7rcewh1pj foreign key (artist_id) references t_artists;
alter table if exists t_tracks add constraint FKhra72vibr08nouki4cijx0tg1 foreign key (cd_id) references t_cds;
